/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Sonidos.Sonido;

/**
 *
 * @author Panky
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jbnt_Start = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Jbtn_opciones = new javax.swing.JButton();
        Jbnt_salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jbnt_Start.setBackground(new java.awt.Color(0, 0, 0));
        Jbnt_Start.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        Jbnt_Start.setForeground(new java.awt.Color(255, 255, 102));
        Jbnt_Start.setText("Start");
        Jbnt_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbnt_StartActionPerformed(evt);
            }
        });
        getContentPane().add(Jbnt_Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 100, 40));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Batman Rogue");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        Jbtn_opciones.setBackground(new java.awt.Color(0, 0, 0));
        Jbtn_opciones.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Jbtn_opciones.setForeground(new java.awt.Color(255, 255, 102));
        Jbtn_opciones.setText("Options");
        Jbtn_opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_opcionesActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn_opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 100, 40));

        Jbnt_salir.setBackground(new java.awt.Color(0, 0, 0));
        Jbnt_salir.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Jbnt_salir.setForeground(new java.awt.Color(255, 255, 102));
        Jbnt_salir.setText("Exit");
        Jbnt_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Jbnt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbnt_salirActionPerformed(evt);
            }
        });
        getContentPane().add(Jbnt_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/original-43b9ff268b3e5a744e91c506d358b29a.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 810, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbnt_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbnt_StartActionPerformed
        Sonido.reproducir("Transicion.wav");
    }//GEN-LAST:event_Jbnt_StartActionPerformed

    private void Jbtn_opcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_opcionesActionPerformed
        Sonido.reproducir("Transicion.wav");
    }//GEN-LAST:event_Jbtn_opcionesActionPerformed

    private void Jbnt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbnt_salirActionPerformed
        Sonido.reproducir("Transicion.wav");
        System.exit(0);
    }//GEN-LAST:event_Jbnt_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbnt_Start;
    private javax.swing.JButton Jbnt_salir;
    private javax.swing.JButton Jbtn_opciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
